### ISSUE TITLE
Configure script?

### ISSUE THREAD

**Issue by kornelski** [psych0der/pngquantjs#3]
What's the problem with the configure script? Can I make it work without the patch?

**Comment by psych0der** [comment]
[Configure script](https://github.com/pornel/pngquant/blob/master/configure#L250) checks for c99 compiler to make sure it is there. But emscripten compiler seemingly fails that test. It's just safe to skip that test, as emscripten compiles it bit code. The configure script being used in this repo is already patched. The patch file is provided just for a reference for compiling against future versions of pngquant.

**Comment by kornelski** [comment]
What error do you get?

I wonder if I can tweak flags to make it work, or should I add a configure option to skip the check. It'd be nice of upstream configure worked out of the box.

**Comment by psych0der** [comment]
The error is as folllows: 
`ERROR:root:no input files
note that input files without a known suffix are ignored, make sure your input files end with one of: ('.c', '.C', '.i', '.cpp', '.cxx', '.cc', '.c++', '.CPP', '.CXX', '.CC', '.C++', '.ii', '.m', '.mi', '.mm', '.mii', '/dev/null', '.bc', '.o', '.obj', '.lo', '.dylib', '.so', '.a', '.ll', '.h', '.hxx', '.hpp', '.hh', '.H', '.HXX', '.HPP', '.HH')
  Compiler: error ... /home/emsdk_portable/emscripten/master/emcc failed to compile anything (make sure it's installed and supports C99)
`
I think an option to bypass this test would do fine.

Also, I wanted pngquant to allow to specify a directory for zlib. I had to put zlib diretory inside pngquant in order to build this. What do you think?

**Comment by kornelski** [comment]
I've made `CC=` argument disable the check: https://github.com/pornel/pngquant/commit/f76fe458b2c796bc1ad93e7c5ef386040a93c180

```sh
./configure CC=/home/emsdk_portable/emscripten/master/emcc
```

should work.

**Comment by kornelski** [comment]
For static linking putting zlib inside pngquant dir is the best option.
